[colors.primary]
background = "#1e1715"
foreground = "#fcc8b4"

[colors.cursor]
cursor = "#fcc8b4"
text = "CellBackground"

[colors.normal]
black   = "#1e1715" # color0
red     = "#fdb171" # color1
green   = "#f7a66b" # color2
yellow  = "#ffba81" # color3
blue    = "#fca968" # color4
magenta = "#f89a4f" # color5
cyan    = "#f58d45" # color6
white   = "#fcc8b4" # color7

[colors.bright]
black   = "#1e1715" # color8
red     = "#a96f5a" # color9
green   = "#f3b874" # color10
yellow  = "#ef9652" # color11
blue    = "#8a3e2d" # color12
magenta = "#ec5832" # color13
cyan    = "#ff8131" # color14
white   = "#fcc8b4" # color15

[cursor]
blink_interval = 270
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Underline"

[font]
size = 4.9

[font.bold]
family = "Jetbrains Mono Nerd Font"

[font.bold_italic]
family = "Jetbrains Mono Nerd Font"

[font.italic]
family = "Jetbrains Mono Nerd Font"

[font.normal]
family = "Jetbrains Mono Nerd Font"

[mouse]
hide_when_typing = true

[window]
blur = true
decorations = "full"
dynamic_padding = false
opacity = 0.82
startup_mode = "Windowed"

[window.padding]
x = 13
y = 13

[general]
live_config_reload = true
ipc_socket = true
