[colors.primary]
background = "#001010"
foreground = "#ddfdff"

[colors.cursor]
cursor = "#a4d7b6"
text = "CellBackground"

[colors.normal]
black   = "#276759" # color0
red     = "#d393d2" # color1
green   = "#3E8355" # color2
yellow  = "#318D73" # color3
blue    = "#b372ad" # color4
magenta = "#53986E" # color5
cyan    = "#a4d7b6" # color6
white   = "#ddfdff" # color7

[colors.bright]
black   = "#357f70" # color8
red     = "#e2a3e0" # color9
green   = "#4ea165" # color10
yellow  = "#3dbf94" # color11
blue    = "#c48abf" # color12
magenta = "#65ad80" # color13
cyan    = "#b9e5cc" # color14
white   = "#ffffff" # color15

[cursor]
blink_interval = 270
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Underline"

[font]
size = 4.7

[font.bold]
family = "Jetbrains Mono Nerd Font"

[font.bold_italic]
family = "Jetbrains Mono Nerd Font"

[font.italic]
family = "Jetbrains Mono Nerd Font"

[font.normal]
family = "Jetbrains Mono Nerd Font"

[mouse]
hide_when_typing = true

[window]
blur = true
decorations = "full"
dynamic_padding = false
opacity = 0.7
startup_mode = "Windowed"

[window.padding]
x = 13
y = 13

[general]
live_config_reload = true
ipc_socket = true
