
[colors.bright]
black = "#938087"
blue = "#AC7891"
cyan = "#C27F94"
green = "#6679A7"
magenta = "#877CA1"
red = "#5F73A1"
white = "#d3b8c1"
yellow = "#906E8D"

[colors.cursor]
cursor = "#d3b8c1"
text = "CellBackground"

[colors.normal]
black = "#0d0d13"
blue = "#AC7891"
cyan = "#C27F94"
green = "#6679A7"
magenta = "#877CA1"
red = "#5F73A1"
white = "#d3b8c1"
yellow = "#906E8D"

[colors.primary]
background = "#0d0d13"
foreground = "#d3b8c1"

[cursor]
blink_interval = 270
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Underline"

[font]
size = 9.0

[font.bold]
family = "Jetbrains Mono Nerd Font"

[font.bold_italic]
family = "Jetbrains Mono Nerd Font"

[font.italic]
family = "Jetbrains Mono Nerd Font"

[font.normal]
family = "Jetbrains Mono Nerd Font"

[mouse]
hide_when_typing = true

[window]
blur = true
decorations = "full"
dynamic_padding = false
opacity = 0.7
startup_mode = "Windowed"

[window.padding]
x = 13
y = 13

[general]
live_config_reload = true
ipc_socket = true
